# 是否开启快速模式，快速模式下仅测试连通性
fast_mode = false

# 待测速的订阅节点
# 支持网络地址 https://xxx
# 支持本地地址（绝对地址）/User/xxx/xx.yml
# 支持单个订阅链接，ss://xxx
subs = [
    "https://raw.githubusercontent.com/ReaJason/Clash-Butler/master/clash.yaml"
    "https://raw.githubusercontent.com/firefoxmmx2/v2rayshare_subcription/main/subscription/clash_sub.yaml"
    "https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc0.yaml"
    "https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc1.yaml"
    "https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc2.yaml"
    "https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc3.yaml"
    "https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc4.yaml"
    "https://raw.githubusercontent.com/xiaoji235/airport-free/refs/heads/main/clash/naidounode.txt"
    "https://raw.githubusercontent.com/mahdibland/SSAggregator/master/sub/sub_merge_yaml.yml"
    "https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity.yml"
    "https://raw.githubusercontent.com/vxiaov/free_proxies/main/clash/clash.provider.yaml"
    "https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta.yaml"
    "https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml"
    "https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml"
    "https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml"
    "https://raw.githubusercontent.com/mgit0001/test_clash/refs/heads/main/heima.txt"
    "https://raw.githubusercontent.com/aiboboxx/v2rayfree/refs/heads/main/README.md"
    "https://raw.githubusercontent.com/shahidbhutta/Clash/refs/heads/main/Router"
    "https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.meta.yml"
    "https://raw.githubusercontent.com/anaer/Sub/refs/heads/main/clash.yaml"
    "https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml"
    "https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.yml"
    "https://raw.githubusercontent.com/mfbpn/tg_mfbpn_sub/main/trial.yaml"
    "https://raw.githubusercontent.com/Ruk1ng001/freeSub/main/clash.yaml"
    "https://raw.githubusercontent.com/SoliSpirit/v2ray-configs/main/all_configs.txt"
    "https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash"
    "https://raw.githubusercontent.com/go4sharing/sub/main/sub.yaml"
    "https://raw.githubusercontent.com/mfuu/v2ray/master/clash.yaml"
]

# 是否重命名节点，打开后会使用 geoip 等方式进行代理真实 IP 和地理地址查询
rename_node = true
rename_pattern = "${COUNTRYCODE}_${CITY}_${ISP}"

# 是否需要加上代理池的节点一起筛选
need_add_pool = true
# 代理节点池
pools = [
    "https://raw.githubusercontent.com/Ruk1ng001/freeSub/main/clash.yaml",
    "https://raw.githubusercontent.com/PuddinCat/BestClash/refs/heads/main/proxies.yaml",
    "https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.txt",
]

# 测试分组大小
test_group_size = 50

# 连通性测试
[connect_test]
url = "http://www.google.com/generate_204"
expected = 204
timeout = 1000

# 带宽测速配置
[speed_test]
enabled = false
url = "https://speed.cloudflare.com/__down?bytes=104857600"
timeout = 3000
